### ISSUE TITLE
Do not know how to do it working

### ISSUE THREAD

**Issue by anquegi** [rocky/realgud-byebug#1]
I'm not sure that this is a bug or not but, I cannot make it working. 
M-x load-library RET realgud RET
=> OK
M-x load-library RET realgud:byebug RET
=> OK
M-X realgud:byebug
run byebug (like this): byebug RET
Wrong tyoe argument, string p nil

I have a byebug session allready running
<img width="1280" alt="screen shot 2016-12-09 at 09 49 08" src="https://cloud.githubusercontent.com/assets/2518346/21042926/c6c34f7c-bdf4-11e6-97e2-e3c20974c5e2.png">
<img width="1280" alt="screen shot 2016-12-09 at 09 46 49" src="https://cloud.githubusercontent.com/assets/2518346/21042927/c6c3b44e-bdf4-11e6-989f-567750da85fa.png">
<img width="1280" alt="screen shot 2016-12-09 at 09 46 26" src="https://cloud.githubusercontent.com/assets/2518346/21042928/c6c3f364-bdf4-11e6-8ea9-3ca345bb3e23.png">

Please, I'm new to realgud so maybe I need some advice on setup this

**Comment by rocky** [comment]
> run byebug (like this): byebug RET

When you invoke byebug like this, at the outset, you need to give a program to debug.

```
$ byebug
*** You must specify a program to debug

  byebug 9.0.5

  Usage: byebug [options] <script.rb> -- <script.rb parameters>
```

The message you got:

> Wrong type argument, string p nil

is Emacs' funny way of saying (I think) that it expected you to give a name of the program to debug (a string) and instead it got nothing (nil).

> I have a byebug session allready running

If the byebug session is run inside an emacs comint shell (M-x shell), then you can have realgud track what's going on in that shell. If the session outside of emacs in a terminal, then not. 

To have emacs track this as a shell, run `M-x realgud-track-mode` and when it prompts you for a debugger name, use `byebug`

**Comment by anquegi** [comment]
Thanks, for this advice and short turorial it works pretty well. 

<img width="1280" alt="screen shot 2016-12-12 at 09 47 13" src="https://cloud.githubusercontent.com/assets/2518346/21093057/1b2dee48-c050-11e6-9286-94dde25bb0c2.png">

So it is impossible to debug launching byebug in other terminal and use realgud. but anyway I will use this. thanks

**Comment by rocky** [comment]
> So it is impossible to debug launching byebug in other terminal and use realgud. 

Well I don't know byebug that well, but other debuggers including the ones I've written for (older versions of) Ruby, have an ability connection to the debugger via a socket or network port. In gdb the command that does this inside an interactive session is called ["gdbserver". ](https://sourceware.org/gdb/onlinedocs/gdb/Server.html)

If byebug provides this, then you can run in a terminal and then on the Emacs side connect via a "client side" program. 

A couple of other things. If you found the information on how to use in byebug useful, consider putting that information in the [realgud-byebug wiki ](https://github.com/realgud/realgud-byebug/wiki/_new) for this project to help others. 

The other thing you can do if this is useful is to star the project. I use the ratings to decide which project to work on next when several projects are in need of work which is often the case. Right now, based on ratings, byebug is the least important or used of any project other project.
