### ISSUE TITLE
Can't disable code listing in input buffer

### ISSUE THREAD

**Issue by muirdm** [rocky/realgud-byebug#3]
The code list/context that byebug shows is a bit redundant since i have the code in its own buffer. I tried setting `set noautolist` to disable code listing, but then the marker in my code buffer didn't update as I debugged. Is there a way to disable the redundant code display in the input buffer and have realgud continue to work?

**Comment by rocky** [comment]
I think realgud needs some sort of indication where the position is. Maybe a workaround is setting the number of lines to display be something like 1. (I don't know if byebug  has such a `set listsize` command like the trepan (and gdb) debuggers do.

**Comment by muirdm** [comment]
Could realgud or realgud-byebug gobble up the context lines to learn the line number and then just not echo them back to the input buffer?

**Comment by rocky** [comment]
If that's what you want to try - have at it!

**Comment by muirdm** [comment]
Thanks. Maybe I will poke at it later.
